name: project-check
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installation
        run: make install

      - name: linting
        run: make lint
